language: php

php: 7.2

before_install:
  - composer install

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - composer validate
  - phpunit --coverage-clover ./build/logs/phpunit_clover.xml --configuration tests/phpunit.xml

# after_script:
# - php vendor/bin/coveralls -v
after_success:
  - travis_retry php ./vendor/bin/php-coveralls --coverage_clover=./build/logs/phpunit_clover.xml --json_path=./build/coveralls-upload.json
